"""Add depth column to soil_measurements table

Revision ID: 77e5d4058f94
Revises: 2f53bc73f0c1
Create Date: 2024-09-21 07:39:20.034016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77e5d4058f94'
down_revision = '2f53bc73f0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soil_measurements', sa.Column(
        'depth', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('soil_measurements', 'depth')
    # ### end Alembic commands ###
